// Session store (notes_sessions table, Neon over HTTP via ./db). No
// Node-only imports (the session id is generated by the caller, not here)
// so this file is safe to import from middleware.js (Edge runtime) as well
// as pages/api/*.js.
import { sql, ensureSchema, iso } from "./db";
import { SESSION_IDLE_MS } from "./auth";


function isExpired(session) {
  return Date.now() - new Date(session.last_seen).getTime() > SESSION_IDLE_MS;
}

function parseDevice(ua = "") {
  let browser = "Unknown browser";
  if (ua.includes("Edg/") || ua.includes("EdgA/") || ua.includes("EdgiOS/")) browser = "Edge";
  else if (ua.includes("OPR/") || ua.includes("Opera")) browser = "Opera";
  else if (ua.includes("SamsungBrowser/")) browser = "Samsung Browser";
  else if (ua.includes("CriOS/")) browser = "Chrome";
  else if (ua.includes("FxiOS/")) browser = "Firefox";
  else if (ua.includes("Chrome/")) browser = "Chrome";
  else if (ua.includes("Firefox/")) browser = "Firefox";
  else if (ua.includes("Safari/") && ua.includes("Version/")) browser = "Safari";

  let os = "Unknown OS";
  if (ua.includes("iPhone")) os = "iPhone";
  else if (ua.includes("iPad")) os = "iPad";
  else if (ua.includes("Android")) os = "Android";
  else if (ua.includes("Windows")) os = "Windows";
  else if (ua.includes("Mac OS X")) os = "Mac";
  else if (ua.includes("Linux")) os = "Linux";

  return `${browser} on ${os}`;
}

export async function getSession(id) {
  if (!id) return null;
  await ensureSchema();
  const [session] = await sql`select * from notes_sessions where id = ${id}`;
  if (!session) return null;
  if (isExpired(session)) {
    await sql`delete from notes_sessions where id = ${id}`;
    return null;
  }
  return session;
}

// `id` is generated by the caller (pages/api/auth.js, a Node-runtime file
// that can freely use Node's crypto.randomUUID()) so this module itself
// stays free of Node-only imports.
export async function createSession(id, ip, userAgent) {
  await ensureSchema();
  await sql`insert into notes_sessions (id, ip, device) values (${id}, ${ip || "unknown"}, ${parseDevice(userAgent)})`;
  return id;
}

export async function touchSession(id) {
  if (!id) return;
  await sql`update notes_sessions set last_seen = now() where id = ${id}`;
}

export async function deleteSession(id) {
  if (!id) return;
  await sql`delete from notes_sessions where id = ${id}`;
}

export async function deleteOtherSessions(currentId) {
  await sql`delete from notes_sessions where id <> ${currentId || ""}`;
}

export async function listSessions() {
  await ensureSchema();
  const rows = await sql`select * from notes_sessions order by last_seen desc`;
  const fresh = rows.filter((s) => !isExpired(s));
  const expiredIds = rows.filter((s) => isExpired(s)).map((s) => s.id);
  if (expiredIds.length) await sql`delete from notes_sessions where id = any(${expiredIds})`;
  return fresh.map((s) => ({ id: s.id, ip: s.ip, device: s.device, createdAt: iso(s.created_at), lastSeen: iso(s.last_seen) }));
}
