// Session store — Supabase-backed (notes_sessions table), same
// pattern as spending-tracker's lib/sessions.js. No Node-only imports (the
// session id is generated by the caller, not here) so this file is safe to
// import from middleware.js (Edge runtime) as well as pages/api/*.js.
import { sbSelect, sbInsert, sbUpdate, sbDelete, sbDeleteIn } from "./supabase";
import { SESSION_IDLE_MS } from "./auth";

const TABLE = "notes_sessions";

function isExpired(session) {
  return Date.now() - new Date(session.last_seen).getTime() > SESSION_IDLE_MS;
}

function parseDevice(ua = "") {
  let browser = "Unknown browser";
  if (ua.includes("Edg/") || ua.includes("EdgA/") || ua.includes("EdgiOS/")) browser = "Edge";
  else if (ua.includes("OPR/") || ua.includes("Opera")) browser = "Opera";
  else if (ua.includes("SamsungBrowser/")) browser = "Samsung Browser";
  else if (ua.includes("CriOS/")) browser = "Chrome";
  else if (ua.includes("FxiOS/")) browser = "Firefox";
  else if (ua.includes("Chrome/")) browser = "Chrome";
  else if (ua.includes("Firefox/")) browser = "Firefox";
  else if (ua.includes("Safari/") && ua.includes("Version/")) browser = "Safari";

  let os = "Unknown OS";
  if (ua.includes("iPhone")) os = "iPhone";
  else if (ua.includes("iPad")) os = "iPad";
  else if (ua.includes("Android")) os = "Android";
  else if (ua.includes("Windows")) os = "Windows";
  else if (ua.includes("Mac OS X")) os = "Mac";
  else if (ua.includes("Linux")) os = "Linux";

  return `${browser} on ${os}`;
}

export async function getSession(id) {
  if (!id) return null;
  const rows = await sbSelect(TABLE, { id: `eq.${id}` });
  const session = rows[0];
  if (!session) return null;
  if (isExpired(session)) {
    await sbDelete(TABLE, "id", id);
    return null;
  }
  return session;
}

// `id` is generated by the caller (pages/api/auth.js, a Node-runtime file
// that can freely use Node's crypto.randomUUID()) so this module itself
// stays free of Node-only imports.
export async function createSession(id, ip, userAgent) {
  await sbInsert(TABLE, [{ id, ip: ip || "unknown", device: parseDevice(userAgent) }]);
  return id;
}

export async function touchSession(id) {
  if (!id) return;
  await sbUpdate(TABLE, "id", id, { last_seen: new Date().toISOString() });
}

export async function deleteSession(id) {
  if (!id) return;
  await sbDelete(TABLE, "id", id);
}

export async function deleteOtherSessions(currentId) {
  const rows = await sbSelect(TABLE, {});
  const otherIds = rows.filter((s) => s.id !== currentId).map((s) => s.id);
  await sbDeleteIn(TABLE, "id", otherIds);
}

export async function listSessions() {
  const rows = await sbSelect(TABLE, { order: "last_seen.desc" });
  const fresh = rows.filter((s) => !isExpired(s));
  const expiredIds = rows.filter((s) => isExpired(s)).map((s) => s.id);
  if (expiredIds.length) await sbDeleteIn(TABLE, "id", expiredIds);
  return fresh.map((s) => ({ id: s.id, ip: s.ip, device: s.device, createdAt: s.created_at, lastSeen: s.last_seen }));
}
